on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
jobs:
  test:
    permissions:
      contents: read
      id-token: write
#    environment: hoge
    runs-on: ubuntu-latest
    steps:
      - name: "Get ID Token"
        run: |
          curl --silent -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" "${ACTIONS_ID_TOKEN_REQUEST_URL}" | sed 's/./& /g'
